In [25]:
import numpy as np
x0 = np.ones(10)
x1 = np.array([64.3,99.6,145.45,63.75,135.46,92.85,86.97,144.76,59.3,116.03])
x2 = np.array([2,3,4,2,3,4,2,4,1,3])
y = np.array([62.55,82.42,132.62,73.31,131.05,86.57,85.49,127.44,55.25,104.84])
X = np.stack((x0,x1,x2),axis=1)
X
Y = y.reshape(10,-1)
Y
X = np.mat(X)
Y = np.mat(Y)
W = (X.T*X).I*X.T*Y
print('X=',X)
print('Y=',Y)
print('W=',W)


X= [[  1.    64.3    2.  ]
 [  1.    99.6    3.  ]
 [  1.   145.45   4.  ]
 [  1.    63.75   2.  ]
 [  1.   135.46   3.  ]
 [  1.    92.85   4.  ]
 [  1.    86.97   2.  ]
 [  1.   144.76   4.  ]
 [  1.    59.3    1.  ]
 [  1.   116.03   3.  ]]
Y= [[ 62.55]
 [ 82.42]
 [132.62]
 [ 73.31]
 [131.05]
 [ 86.57]
 [ 85.49]
 [127.44]
 [ 55.25]
 [104.84]]
W= [[10.72771277]
 [ 0.87654538]
 [-1.7752445 ]]


In [3]:
x0

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [6]:
x1

array([ 64.3 ,  99.6 , 145.45,  63.75, 135.46,  92.85,  86.97, 144.76,
        59.3 , 116.03])

In [8]:
x2

array([2, 3, 4, 2, 3, 4, 2, 4, 1, 3])

In [10]:
y

array([ 62.55,  82.42, 132.62,  73.31, 131.05,  86.57,  85.49, 127.44,
        55.25, 104.84])

In [20]:
Y

array([[ 62.55],
       [ 82.42],
       [132.62],
       [ 73.31],
       [131.05],
       [ 86.57],
       [ 85.49],
       [127.44],
       [ 55.25],
       [104.84]])